export default {
    subjects: ["","语文", "数学", "英语", "物理", "化学", "政治", "历史", "地理", "生物", "体育", "美术", "音乐", "其他", "科学", "思想品德", "信息", "社会", "健康", "书法"],
    gradeNames: ["小学一年级", "小学二年级", "小学三年级", "小学四年级", "小学五年级", "小学六年级", "初一", "初二", "初三", "高一", "高二", "高三", "管理组", "大一", "大二", "大三", "大四", "研一", "研二", "研三", "研四", "学前班", "小班", "中班", "大班", "毕业班", "毕业班"],
    gradeNamesToPick: ["小学一年级", "小学二年级", "小学三年级", "小学四年级", "小学五年级", "小学六年级", "初一", "初二", "初三", "高一", "高二", "高三", "管理组", "大一", "大二", "大三", "大四", "研一", "研二", "研三", "研四", "学前班", "小班", "中班", "大班"],
    allWorkType: [
        {
            type: 1,
            name: "作业",
            icon: "https://img.lulufind.com/mrzy_wtype_work_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_work_1.png"
        }, {
            type: 2,
            name: "打卡",
            icon: "https://img.lulufind.com/mrzy_wtype_daka_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_daka_1.png"
        }, {
            type: 3,
            name: "扫描卡",
            icon: "https://img.lulufind.com/mrzy_wtype_scan_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_scan_1.png"
        }, {
            type: 4,
            name: "考试",
            icon: "https://img.lulufind.com/mrzy_wtype_exam_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_exam_1.png"
        }, {
            type: 5,
            name: "问卷",
            icon: "https://img.lulufind.com/mrzy_wtype_q_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_q_1.png"
        }, {
            type: 6,
            name: "点评",
            icon: "https://img.lulufind.com/mrzy_wtype_comment_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_comment_1.png"
        }, {
            type: 7,
            name: "小红花",
            icon: "https://img.lulufind.com/mrzy_wtype_red_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_red_1.png"
        }, {
            type: 8,
            name: "奖状",
            icon: "https://img.lulufind.com/mrzy_wtype_award_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_award_1.png"
        }, {
            type: 9,
            name: "动态",
            icon: "https://img.lulufind.com/mrzy_wtype_notif_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_notif_1.png"
        }, {
            type: 10,
            name: "相册",
            icon: "https://img.lulufind.com/mrzy_wtype_album_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_album_1.png"
        }, {
            type: 11,
            name: "健康",
            icon: "https://img.lulufind.com/mrzy_wtype_health_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_health_1.png"
        }, {
            type: 12,
            name: "讲解",
            icon: "https://img.lulufind.com/mrzy_wtype_lupin_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_lupin_1.png"
        }, {
            type: 13,
            name: "成绩",
            icon: "https://img.lulufind.com/mrzy_wtype_grade_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_grade_1.png"
        }, {
            type: 14,
            name: "学情打分",
            icon: "https://img.lulufind.com/mrzy_wtype_score_0.png",
            icon_active: "https://img.lulufind.com/mrzy_wtype_score_0.png"
        }, {
            type: 15,
            name: "通知",
            icon: "https://img.lulufind.com/static/icon_1.png",
            icon_active: "https://img.lulufind.com/static/icon_1.png"
        }],
}
